### PR TITLE
Ensuring Student Email and Student ID come from the same Roster Student

### LINKED ISSUE #47: Finish out CRUD for Roster student (still need Update and Delete).
We have Create and Read for Roster student, but we are still missing Update and Destroy.

Implement Update, but only allow updates to:

* First name
* Last name
* Student number (check if the new student number would result in a duplicate)

DO NOT allow updates to email for now, since this could break some linkages.  For now, if you enter an email wrong, you have to delete and re add the roster student.  (We might fix this later so that errors in emails can be addressed without deleting and reentering).

Implement Delete, but think carefully about preserving the integrity of  other database tables.

These could be implemented as separate PRs (in which case it may make sense to make two subissues: one for Update, and one for Delete.)

### LINKED ISSUE #278: BUG: It is currently possible to create two Roster Student records for the same course with duplicate emails.
Steps to reproduce:

(1) Make sure there is at least one existing roster student with any email, for sake of argument, studfent id 12345 aaa@ucsb.edu.

(2) Under "Create single roster student", enter a student with a different student id and email, say, 54321 email bbb@ucsb.edu.

(3) Still under create roster student, enter a student with student id 12345 (the pre-existing student) and email bbb@ucsb.edu.

Observed: You will now have two students with different student ids, but the same email.

Desired: That should not be possible.   Probably, when manually entering or editing either a student id or an email, if it duplicates the id or email of any other existing student, it should be rejected.   This should be enforced in the single POST and single PUT endpoints.

For the CSV upload: if there is already a match on both id and email, then treat it as an upsert, and just update the other fields that may be present (e.g. change it to ROSTER rather than MANUAL, and update the name fields.)

If there is a match on id, but NOT on email, then as long as the the email doesn't duplicate one already in the database, treat it as an upsert on the existing student.   

If there's match on email but not id, and the id doesn't duplicate another one already in the database treat it as an upsert.

The error conditions are:
* Email and id match different existing students; unable to add record"

Otherwise, add the failure to a list of "failures", and at the end of the operation, report back a json object that contains:

```
  { "new_roster_students" : 35,
    "roster_students_updated": 15,
    "errors": 5,
    "error_detail': [
       "id xxxxxx and email yyyyy@ucsb.edu both match different existing roster students for course with id x",
       "id aaaaaa and email yyyyy@ucsb.edu both match different existing roster students for course with id x",
       "id xxxxxx and email nnnnn@ucsb.edu both match different existing roster students for course with id x",
       "id jjjjjj and email ppppp@ucsb.edu both match different existing roster students for course with id x",
    ]
````

### PR DESCRIPTION
**Pull request by Division7**
In this PR, I ensure that roster students submitted by CSV and POST are consistent in the database. When submitted, the method checks if there is already a Roster Student with that email and a Roster Student with that Student ID. If they are the same, it updates them. If they come from different Roster Students, it rejects it. They are then added to the list of rejected Roster Students, for the Instructor to handle.

The frontend will currently fail silently, but this is not a common bug.
## Testing Plan
1. Clear the Roster Students for a course
2. Upload a roster student with the ID `A123456`
3. Upload a different roster student with the email `cgaucho@ucsb.edu`
4. Try to upload the `egrades.csv`
5. Ensure that the Chris Fake roster student has not been created.

Deployed to: https://frontiers-qa2.dokku-00.cs.ucsb.edu/

Closes #278 
Closes #47

### CODE REVIEW

File: src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java [hunk 1]
```diff
@@ -209,16 +214,18 @@ public Map<String, String> uploadRosterStudentsCSV(
...
-    return Map.of(
-        "filename", file.getOriginalFilename(),
-        "message",
-            String.format(
-                "Inserted %d new students, Updated %d students",
-                counts[InsertStatus.INSERTED.ordinal()], counts[InsertStatus.UPDATED.ordinal()]));
+    return new LoadResult(
+        counts[InsertStatus.INSERTED.ordinal()],
+        counts[InsertStatus.UPDATED.ordinal()],
+        rejectedStudents);
```
Comment (pconrad) [inline src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java:228]: What if we did something like this:
```suggestion
    LoadResult loadResult = new LoadResult(
        counts[InsertStatus.INSERTED.ordinal()],
        counts[InsertStatus.UPDATED.ordinal()],
        rejectedStudents);
    if (rejectStudents.length() > 0) {
       throw new RejectedStudentsException(loadResult);
    }
    return loadResult;
```

Then we can add an Exception Handler in the ApiController to catch this, and format a nice error message for the end user.   I agree that it's not a common error message, but failing silently, when it comes to getting students into the course, sounds like... well, "not ideal" is how I'll phrase it, but I'm being "diplomatic" :-)

**Review by pconrad — CHANGES_REQUESTED** [review]
I have a suggestion...

File: src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java (hunk 1 above)
Comment (pconrad) [reply src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java:228]: I think we agree that throwing an exception is overkill in the long run.. that it would be better to simply process the output of the request on the client side and throw it up in a modal... and it occurs to me that building a mechanism for this could also be leveraged for the CSV team upload, where there are similar issues, and the same data structure... 

It might be worth it to just go ahead and build that, especially if it can be reused when we build the frontend for PR #316.

But I'll leave it up you.

**Review by pconrad — APPROVED** [review]
LGTM.. tested on Dokku
