### PR TITLE
FEATURE/BUG:  admins can authorize GitHub apps

### LINKED ISSUE #135: BUG: Admins cannot Install GitHub Applications to other Courses
Currently, the only person who can install a GitHub application to a course is the person who created it. 

We should decide the following:
a) should this check be removed?
b) should it be loosened so that admins can install on any course?
c) should the frontend display the option to install on courses in which the user does not have permissions?

### PR DESCRIPTION
**Pull request by pconrad**
In this PR, we refactor the workflow for instructors and admins to link courses to a Github Organization.

1. The Admin/Courses menuitem is now the Instructor/Courses menu item.
2. This page now shows all courses for Admins, and for instructors, only their own courses.
3. Admins can link any course.   Instructors can only link their own courses.
4. The page no longer has an installation id column, because that information is not interesting or useful for end users.
5. We use a single column for the Github org.  That column contains the button to link the organization if it hasn't been linked yet.
6. The table also shows the instructor of the course.

deployed to https://frontiers-qa.dokku-00.cs.ucsb.edu

closes #135 #143 #144 

In this PR, we address a permissions issue with linking courses to github apps.

# Test Plan

Test 1:  Users with INSTRUCTOR can create a course and install it

* Create a user with the INSTRUCTOR role but not the ADMIN role
* Create a course with that user
* Install a github app

Test 2: Requires two testers

* User A has Admin, User B has admin
* User A creates the course.  Test that Users B can install the app to a github org

Test 3: Requires two testers:
* User A has Instructor access, and creates a course.
* User B has Instructor access and creates a courses

* User A  can only see the course(s) they created, and can install any of them
* User B  can only see the course(s) they created, and can install any of them.

### CODE REVIEW

File: src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java [hunk 1]
```diff
@@ -127,7 +128,7 @@ public Iterable<Course> allCourses() {
      *
      */
     @Operation(summary = "Authorize Frontiers to a Github Course")
-    @PreAuthorize("hasRole('ROLE_PROFESSOR')")
+    @PreAuthorize("hasRole('ROLE_ADMIN') || hasRole('ROLE_PROFESSOR')")
```
Comment (Division7) [inline src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java:131]: Since the professor/instructor role is implied by admin we may want to consider keeping it as just professor

Comment (pconrad) [reply src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java]: Technically, yes; it is unnecessary.  But from the standpoint of efficiency it costs very little, and for making the code more understandable, it may help.

File: src/main/java/edu/ucsb/cs156/frontiers/controllers/ApiController.java [hunk 2]
```diff
@@ -32,6 +36,25 @@ protected CurrentUser getCurrentUser() {
...
   }
 
+/**
+   * This method checks if the current user has the given role
+   * @return true if the current user has the role, false otherwise
+   * @param role the role to check
+   */
+  protected boolean doesCurrentUserHaveRole(String roleToCheck) {  
+    return getCurrentUser().getRoles().stream()
+        .anyMatch(role -> role.getAuthority().equals(roleToCheck));
```
[the remark this answers is not in the document]
Comment (pconrad) [reply src/main/java/edu/ucsb/cs156/frontiers/controllers/ApiController.java]: Good catch! Fixed

**Review by Division7 — APPROVED** [review]
LGTM!
